# -*- auto-fill-function: nil; eval: (add-hook 'after-save-hook 'org-babel-tangle nil t); -*-

So, we're learning Web Dev.
Well, at least /I/ am!

Let's make it easier and more fun with Literate Programming in Org Mode.

Starting from the fundamentals.
Web pages are all about navigating through content.
To make things easier, we have:
- HTML, for /structure/;
- CSS, for /style/;
- Javascript, for /logic/.


A minimal html page [[https://html.spec.whatwg.org/multipage/syntax.html?utm_source=chatgpt.com#writing][must have]]:

#+begin_src html
<!DOCTYPE html>
<html>
</html>
#+end_src

Here:
- ~<!DOCTYPE html>~ is the /Document type declaration/; it tells the browser the specifications that the page follows.
- ~<html>~ and ~</html>~ enclose the page itself.

The fundamental element of a web page is... well, an =element=.
By definition, an =element= is composed by (example inside the parentheses):
- opening tag (~<html>~);
- everything in between (called /content/);
- closing tag (~</html>~).

The page is made of a sequence of elements.

Some elements may be /empty/: they don't have a closing tag.
Example: ~<!DOCTYPE html>~.

A /cool/ first web page would be:

~hello-world.html ≡~

#+begin_src html :tangle hello-world.html
<!DOCTYPE html>
<html>
  <p>Hello, World!</p>
</html>
#+end_src

*Note*: Here the contents of the =element= ~<p>~ are "Hello, world!".
